#!/bin/sh
ORACLE_SID=rcat ; ORAENV_ASK=NO
export ORACLE_SID ORAENV_ASK

. oraenv

svrmgrl << EOF
spool crdb2.log
connect internal
@$ORACLE_HOME/rdbms/admin/catalog.sql;

REM *********Create Initial RBS****************
CREATE ROLLBACK SEGMENT r0 TABLESPACE SYSTEM
STORAGE (INITIAL 16K NEXT 16K MINEXTENTS 2 MAXEXTENTS 20);
ALTER ROLLBACK SEGMENT r0 ONLINE;   

REM ********** ALTER SYSTEM TABLESPACE *********
ALTER TABLESPACE SYSTEM
DEFAULT STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0);

REM ********** TABLESPACE FOR Tool **********
CREATE TABLESPACE TOOLS DATAFILE '/oradata/data/rcat/tools01.dbf' SIZE 10M 
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M ;
ALTER DATABASE DATAFILE '/oradata/data/rcat/tools01.dbf' AUTOEXTEND OFF;

REM ********** TABLESPACE FOR ROLLBACK **********
CREATE TABLESPACE RBS DATAFILE '/oradata/data/rcat/rbs01.dbf' SIZE 100M 
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 2M ;
ALTER DATABASE DATAFILE '/oradata/data/rcat/rbs01.dbf' AUTOEXTEND OFF;

REM ********** TABLESPACE FOR TEMPORARY **********
CREATE TEMPORARY TABLESPACE TEMP TEMPFILE '/oradata/data/rcat/temp01.dbf' SIZE 100M 
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M ;
ALTER DATABASE TEMPFILE '/oradata/data/rcat/temp01.dbf' AUTOEXTEND OFF;

REM ********** TABLESPACE FOR USER **********
CREATE TABLESPACE USERS DATAFILE '/oradata/data/rcat/users01.dbf' SIZE 10M 
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M ;
ALTER DATABASE DATAFILE '/oradata/data/rcat/users01.dbf' AUTOEXTEND OFF;

REM ********** TABLESPACE FOR RMAN **********
CREATE TABLESPACE RCAT DATAFILE '/oradata/data/rcat/rcat.dbf' SIZE 50M 
DEFAULT STORAGE ( INITIAL 100k NEXT 100k MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0);
ALTER DATABASE DATAFILE '/oradata/data/rcat/rcat.dbf' AUTOEXTEND OFF;

REM **** Creating rollback segments ****************
CREATE PUBLIC ROLLBACK SEGMENT R01 TABLESPACE RBS
STORAGE ( OPTIMAL 4096K );
CREATE PUBLIC ROLLBACK SEGMENT R02 TABLESPACE RBS
STORAGE ( OPTIMAL 4096K );
CREATE PUBLIC ROLLBACK SEGMENT R03 TABLESPACE RBS
STORAGE ( OPTIMAL 4096K );
CREATE PUBLIC ROLLBACK SEGMENT R04 TABLESPACE RBS
STORAGE ( OPTIMAL 4096K );
CREATE PUBLIC ROLLBACK SEGMENT R05 TABLESPACE RBS
STORAGE ( OPTIMAL 4096K );
CREATE PUBLIC ROLLBACK SEGMENT R06 TABLESPACE RBS
STORAGE ( OPTIMAL 4096K );
CREATE PUBLIC ROLLBACK SEGMENT R07 TABLESPACE RBS
STORAGE ( OPTIMAL 4096K );
CREATE PUBLIC ROLLBACK SEGMENT R08 TABLESPACE RBS
STORAGE ( OPTIMAL 4096K );
CREATE PUBLIC ROLLBACK SEGMENT R09 TABLESPACE RBS
STORAGE ( OPTIMAL 4096K );
CREATE PUBLIC ROLLBACK SEGMENT R10 TABLESPACE RBS
STORAGE ( OPTIMAL 4096K );
CREATE PUBLIC ROLLBACK SEGMENT R11 TABLESPACE RBS
STORAGE ( OPTIMAL 4096K );
CREATE PUBLIC ROLLBACK SEGMENT R12 TABLESPACE RBS
STORAGE ( OPTIMAL 4096K );
CREATE PUBLIC ROLLBACK SEGMENT R13 TABLESPACE RBS
STORAGE ( OPTIMAL 4096K );
CREATE PUBLIC ROLLBACK SEGMENT R14 TABLESPACE RBS
STORAGE ( OPTIMAL 4096K );
CREATE PUBLIC ROLLBACK SEGMENT R15 TABLESPACE RBS
STORAGE ( OPTIMAL 4096K );

ALTER ROLLBACK SEGMENT "R01" ONLINE;
ALTER ROLLBACK SEGMENT "R02" ONLINE;
ALTER ROLLBACK SEGMENT "R03" ONLINE;
ALTER ROLLBACK SEGMENT "R04" ONLINE;
ALTER ROLLBACK SEGMENT "R05" ONLINE;
ALTER ROLLBACK SEGMENT "R06" ONLINE;
ALTER ROLLBACK SEGMENT "R07" ONLINE;
ALTER ROLLBACK SEGMENT "R08" ONLINE;
ALTER ROLLBACK SEGMENT "R09" ONLINE;
ALTER ROLLBACK SEGMENT "R10" ONLINE;
ALTER ROLLBACK SEGMENT "R11" ONLINE;
ALTER ROLLBACK SEGMENT "R12" ONLINE;
ALTER ROLLBACK SEGMENT "R13" ONLINE;
ALTER ROLLBACK SEGMENT "R14" ONLINE;
ALTER ROLLBACK SEGMENT "R15" ONLINE;


REM **** SYS and SYSTEM users ****************
alter user sys temporary tablespace TEMP;
alter user system temporary tablespace TEMP;
disconnect
spool off
exit


EOF
